import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar';
import { Toaster } from "sonner";
import { SessionProvider } from "@/components/AuthProvider";
import { auth } from "@/auth"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Captions Generator",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className + " bg-gradient-to-r from-blue-800 to-indigo-900 min-h-screen text-gray-100"}>
        <main className="px-4 py-6">
          <Navbar />
          <Toaster />
          <SessionProvider session={session}>
            {children}
          </SessionProvider>
        </main>
      </body>
    </html>
  );
}
